sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "stable"
env:
  - NPM_VERSION=4
  - NPM_VERSION=3
before_install:
  - npm install -g npm@$NPM_VERSION
before_script:
  - npm install
script:
  - npm test